name: CI/CD

on:
  push:
    branches: [ master ]
    paths:
      - "GesetzeAPI-application/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
    - name: run JUnit 5 Maven tests
      run: mvn clean test

  deploy:
    runs-on: ubuntu-latest
    
    needs: [test]
    
    steps:
      - uses: actions/checkout@v2
      - name: CapRover App Deploy
        uses: floms/action-caprover@v1
        with:
          host: https://captain.luis.team
          password: ${{ secrets.CAPROVER_PASSWORD }}
          app: gesetzeapi
          branch: master
          
  push_to_dockerhub_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    
    needs: [test]
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: luuuuuis
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: luuuuuis/gesetzeapi
          tag_with_ref: true
