name: CD Application to server

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - "GesetzeAPI-application/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: CapRover App Deploy
        uses: floms/action-caprover@v1
        with:
          host: https://captain.luis.team
          password: ${{ secrets.CAPROVER_PASSWORD }}
          app: gesetzeapi
          branch: master
